mysql:
  user: ****
  password: ******
  dsn:  root:******@tcp(***.***.***.***:11263)/unionsdk?charset=utf8
redis:
  addr: ***.***.***.***:16379
  password: ******
  DB: 3
  poolSize: 30
  minIdleConn:  30
